- name: Install dependencies
  pip:
    name: pyapi-gitlab

- name: Open session
  uri:
    url: http://{{ gl_url }}/api/v3/session
    method: POST
    body: "login={{ gl_username }}&password={{ gl_password }}"
    status_code: 201
  register: session

- include: registerrunner.yml
- include: createproject.yml
