- name: Download runner page
  get_url:
    url: http://{{ gl_hostname }}/admin/runners
    dest: /tmp/runnerpage.html
    headers: "PRIVATE-TOKEN: {{ session.json.private_token }}"
    force: true

- name: Get runners-token
  shell: >
    grep -o '<code id="runners-token">.*</code>' /tmp/runnerpage.html |
    sed 's/\(<code id="runners-token">\|<\/code>\)//g'
  register: runnerstoken
  changed_when: false

- name: Start and Register Gitlab CI Runner
  shell: >
    docker exec
    gitlab-runner
    gitlab-ci-multi-runner register -n
    --url http://{{ gl_ip }}/
    --registration-token {{ runnerstoken.stdout }}
    --tag-list test
    --description testrunner
    --executor docker
    --docker-image alpine:latest
    --docker-extra-hosts {{ gl_hostname}}:{{ gl_ip }}
    2>&1
  register: result
  failed_when: "'Runner registered successfully.' not in result.stdout"
  changed_when: true
