---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible & ansible-lint
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook playbook.yml --syntax-check
  - ansible-lint playbook.yml
