---
- name: Setup Gitlab with Gitlab-CI-runner
  hosts: localhost
  gather_facts: false
  vars:
    gl_url: localhost
    gl_username: root
    gl_password: password
    project_name: hello-world
  roles:
    - docker
    - gitlab
